---
language: c

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt update
  - sudo apt install -y ansible

script:
  - cd tests
  - docker-compose up -d
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook site.yml
  - ansible-playbook site.yml

before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
