---
language: python

services:
  - docker

python:
  - "2.7"
  - "3.6"
  - "3.7"

env:
  - REQUIREMENTS_FILE=requirements-2.4.txt
  - REQUIREMENTS_FILE=requirements-2.5.txt
  - REQUIREMENTS_FILE=requirements-2.6.txt
  - REQUIREMENTS_FILE=requirements-2.7.txt

install:
  - pip install -r "$REQUIREMENTS_FILE"

script:
  - molecule test
