---
language: python

services:
  - docker

python:
  - "3.7"

env:
  - REQUIREMENTS_FILE=requirements-2.5.txt
  - REQUIREMENTS_FILE=requirements-2.6.txt
  - REQUIREMENTS_FILE=requirements-2.7.txt
  - REQUIREMENTS_FILE=requirements-2.8.txt

install:
  - pip install -r "$REQUIREMENTS_FILE"

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
