version: 2.1
jobs:
  build:
    machine: true
    environment:
      REQUIREMENTS_FILE: requirements-2.8.txt
    steps:
      - checkout
      - run: 
          name: "Install Python Version"
          command: | 
            pyenv update
            pyenv install 3.7.0
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          name: "Install dependencies"
          command: pip install -r ${REQUIREMENTS_FILE}
      - run:
          name: "Run Molecule Test"
          command: molecule test