version: 2.1
jobs: 
  build:
    docker: 
      - image: circleci/python:3.7
        environment: 
          REQUIREMENTS_FILE: requirements-2.8.txt
    steps:
      - checkout
      - run: 
          command:  |
            pip install -r ${REQUIREMENTS_FILE}
            molecule test

            