---
- src: geerlingguy.swap
<<<<<<< HEAD
  version: 1.0.1

- src: jnv.unattended-upgrades
  version: v1.7.1
=======
  version: 1.0.0

- src: jnv.unattended-upgrades
  version: v1.3.0
>>>>>>> fd90059... adding molecule scenario for bash_history tasks

- src: nickjj.fail2ban
  version: v0.1.2
